# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Road2ParcsBCN
                                 A QGIS plugin
 Arriba al teu parc més proper de manera còmoda, neta i ràpida
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-18
        copyright            : (C) 2020 by Valentín Sastre Calvi
        email                : vsastrecalvi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Road2ParcsBCN class from file Road2ParcsBCN.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .road2parcs import Road2ParcsBCN
    return Road2ParcsBCN(iface)
